project: exakat
project_name: exakat
project_themes:
  - Exakat
  - ruleset_0
ignore_dirs:
  - /tests
  - /data
  - /human
  - /docs
file_extensions:
  - php
rulesets:
  Exakat :
  - Structures/AddZero
  - Structures/MultiplyByOne
  ruleset_0: # 0 errors found
       "Access Protected Structures": Classes/AccessProtected
       "Accessing Private": Classes/AccessPrivate
       "Adding Zero": Structures/AddZero
       "Aliases Usage": Functions/AliasesUsage
       "Already Parents Interface": Interfaces/AlreadyParentsInterface
       "Altering Foreach Without Reference": Structures/AlteringForeachWithoutReference
       "Ambiguous Array Index": Arrays/AmbiguousKeys
       "Assert Function Is Reserved": Php/AssertFunctionIsReserved
       "Assign Default To Properties": Classes/MakeDefault
       "Assign With And": Php/AssignAnd
       "Avoid Parenthesis": Structures/PrintWithoutParenthesis
